import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '../styles/Home.module.css'

import Layout from '../components/layout';
import Landing from '../components/landing';
import Navigation from '../components/navbar';
import Projects from '../components/projects';

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Navigation className={styles.navigation} />
            <main className={styles.main}>
                <Landing className={styles.landing} />
                <Projects className={styles.projects} />
            </main>
        </>
    )
}
