import { useRouter } from 'next/router';
import Head from 'next/head';
import { Oswald } from '@next/font/google';

import Layout from '../../components/layout';
import styles from '../../styles/Notes.module.css';

const font = Oswald({ subsets: ['latin'] });

export default function Note() {
  const router = useRouter()
  const { pid } = router.query

    return(
	<>
            <Head>
                <title>Faruk Becirovic</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <meta
                    name="viewport"
                    content="width=device-width, initial-scale=1"
                />
                <link rel="icon" href="/icon.svg" />
            </Head>
            <Layout>
                <main
                    className={styles.main + " " + font.className}
                >
                    <p>{pid}</p>
                </main>
            </Layout>
        </>
    );
}
