import Head from 'next/head';
import Image from 'next/image';
import { Oswald } from '@next/font/google';
import styles from '../../styles/Notes.module.css';

import Note from '../../components/project';
import Layout from '../../components/layout';

const font = Oswald({ subsets: ['latin'] })

export default function Notes() {
    return (
        <>
            <Head>
                <title>Faruk Becirovic</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <meta
                    name="viewport"
                    content="width=device-width, initial-scale=1"
                />
                <link rel="icon" href="/icon.svg" />
            </Head>
            <Layout>
                <main
                    className={styles.main + " " + font.className}
                >
                    <h1>Notes</h1>
                    <p>
                        These are the notes I have made for some of
                        the classes I have taken at the university
                        or for some of my personal projects.
                    </p>
                    <div className={styles.notes}>
                        <Note
                            className={styles.card}
                            projectTitle="Project 1"
                            projectDesc="Short description of a project"
                            link="https://github.com/faruk-becirovic?tab=repositories"
                        />
                        <Note
                            className={styles.card}
                            projectTitle="Project 2"
                            projectDesc="Short description of a project"
                            link="https://github.com/faruk-becirovic?tab=repositories"
                        />
                        <Note
                            className={styles.card}
                            projectTitle="Project 3"
                            projectDesc="Short description of a project"
                            link="https://github.com/faruk-becirovic?tab=repositories"
                        />
                    </div>
                </main>
            </Layout>
        </>
    )
}
